name: bookstore
description: Navigation and routing sample app
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0-0

dependencies:
  adaptive_navigation: ^0.0.3
  cupertino_icons: ^1.0.2
  auto_route: ^9.3.0+1
  flutter:
    sdk: flutter
  go_router: ^14.0.0
  url_launcher: ^6.1.1
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  analyzer: ^7.3.0
  auto_route_generator: ^9.3.1
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  test: ^1.24.0

flutter:
  uses-material-design: true
